# Generated by Django 5.0.6 on 2024-07-26 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/iop.png', upload_to='avatars', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('caption', models.CharField(blank=True, max_length=123, verbose_name='légende')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
